# 截断模式配置：运行到截断点，然后切换到新参数
# 使用方法：python experiments/run_with_truncation.py --config config/apply_truncation.yaml --mode truncate

# 截断配置
truncation:
  batch_id: 3350  # 单个截断点（不能是列表）
  
  # 截断后的新生成配置
  new_generation:
    types: "{(20,20,5.1)}"        # 与探索实验相同的types格式
    rate_list: [3.8]               # 覆盖到达率：5.1 -> 1.1
    num_requests: 20000            # 生成10000个新请求
    seed: 123                      # 不同的随机种子

system:
  M_total: 10000
  B: 10000
  d_0: 0.003
  d_1: 0.00032

control:
  queue_policy: FCFS
  preemption_mode: sacrifice
  preemption_strategy: aggressive
  allow_waiting_preempt: false
  victim_policy: LIFO

data:
  request_file: data/input/explore.csv  # 使用explore模式生成的初始请求
  experiments_dir: data/experiments
  L_filter: null

experiment:
  seed: 42
  verbose: true
  progress_interval: 100