# Step 1: 运行实验并保存状态
# python experiments/run_advanced_with_generation.py --config config/step1_save_state.yaml

generation:
  enabled: true
  types: "{(20,20,5.1)}"
  num_requests: 20000
  output: "data/input/generated.csv"
  seed: 42

state_save:
  enabled: true                    # 开启状态保存
  batch_ids: [2950,3000,3020,3030]  # 在这些批次保存状态
  save_completed: true

initial_state:
  enabled: false                   # 不加载初始状态

system:
  M_total: 10000
  B: 10000
  d_0: 0.003
  d_1: 0.00032

control:
  queue_policy: FCFS
  preemption_mode: sacrifice
  preemption_strategy: aggressive
  allow_waiting_preempt: false
  victim_policy: LIFO

data:
  request_file: data/input/generated.csv
  experiments_dir: data/experiments
  L_filter: null

experiment:
  seed: 42
  verbose: true
  progress_interval: 100